;;; aws-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from aws.el

(autoload 'aws-s3-list "aws" "\
List AWS S3 buckets" t)
(register-definition-prefixes "aws" '("aws-"))


;;; Generated autoloads from flycheck_aws.el

(autoload 'aws-s3-list "flycheck_aws" "\
List AWS S3 buckets" t)
(register-definition-prefixes "flycheck_aws" '("aws-"))


;;; End of scraped data

(provide 'aws-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; aws-autoloads.el ends here
