name: "Emacs CI"
on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - 28.1
          - snapshot

    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v2

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        run: |
          # Adding `nixpkgs-unstable` channel for more up-to-date binaries, skip this if you already have `nixpkgs-unstable` in your channel list
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable
          nix-channel --update
          nix-env -iA nixpkgs-unstable.babashka

      - name: Setup eldev
        run: bb install-eldev

      - name: Install dependencies
        run: bb prepare

      - name: Lint
        #if:  matrix.emacs_version != 27.2
        run: bb lint

      - name: Test
        run: bb test
