name: "Emacs CI"
on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - 28.1
          - snapshot

    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v2

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/org-roam/org-roam/master/github-eldev | sh

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.9.162

      - name: Install dependencies
        run: bb prepare

      - name: Lint
        #if:  matrix.emacs_version != 27.2
        run: bb lint

      - name: Test
        run: bb test
